### PR TITLE
LOG-2415: Data-Sink-Client: add newlines when posting data

### PR DESCRIPTION
**Pull request by me**
Add newlines to data-sink output

===

Jira story [#LOG-2415](https://deliveroo.atlassian.net/browse/LOG-2415) in project *Logistics*:

> The direct Firehose-Kinesis bridge doesn't add newlines after each item. This makes it somehow more difficult to parse the resulting files.
> 
> Add the option to add newlines from the data-sink-client.

### CODE REVIEW

**Review by pedrocunha — APPROVED** [review]

**Comment by Antti** [comment]
@me what is this waiting for?

**Comment by me** [comment]
@Antti nothing, I forgot about it :)

**Comment by me** [comment]
@Antti I was waiting for @pedrocunha to set up staging (and then forgot about it 😊 )

**Comment by me** [comment]
@humzashah why was this closed? What are the plans?

**Comment by humzashah** [comment]
~@me, stupid mistake. https://github.com/deliveroo/routemaster-blackhole/pull/8~

This wasn't needed anymore. https://github.com/deliveroo/routemaster-blackhole/blob/master/Gemfile.lock#L16

**Pull request closed without merging**
